const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('lightterm', {
  appGetStorage: () => ipcRenderer.invoke('app:get-storage'),
  appGetStorageMeta: () => ipcRenderer.invoke('app:get-storage-meta'),
  appRefreshStorageData: () => ipcRenderer.invoke('app:refresh-storage-data'),
  appPickStorageFolder: () => ipcRenderer.invoke('app:pick-storage-folder'),
  appPickStorageFile: () => ipcRenderer.invoke('app:pick-storage-file'),
  appPickStorageSaveFile: () => ipcRenderer.invoke('app:pick-storage-save-file'),
  appSetStorageFolder: (payload) => ipcRenderer.invoke('app:set-storage-folder', payload),
  appCreateBackup: () => ipcRenderer.invoke('app:create-backup'),
  appListBackups: () => ipcRenderer.invoke('app:list-backups'),
  appRestoreBackup: (payload) => ipcRenderer.invoke('app:restore-backup', payload),
  appRestart: () => ipcRenderer.invoke('app:restart'),
  appOpenExternal: (payload) => ipcRenderer.invoke('app:open-external', payload),
  appOpenBackupsFolder: () => ipcRenderer.invoke('app:open-backups-folder'),
  clipboardRead: () => ipcRenderer.invoke('clipboard:read'),
  clipboardWrite: (payload) => ipcRenderer.invoke('clipboard:write', payload),
  auditList: (payload) => ipcRenderer.invoke('audit:list', payload),
  auditAppend: (payload) => ipcRenderer.invoke('audit:append', payload),
  auditClear: () => ipcRenderer.invoke('audit:clear'),
  onAuditAppended: (handler) => ipcRenderer.on('audit:appended', (_event, data) => handler(data)),
  updateGetState: () => ipcRenderer.invoke('update:get-state'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateDownload: () => ipcRenderer.invoke('update:download'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  onUpdateStatus: (handler) => ipcRenderer.on('update:status', (_event, data) => handler(data)),
  onStorageDataChanged: (handler) => ipcRenderer.on('storage:data-changed', (_event, data) => handler(data)),

  hostsList: () => ipcRenderer.invoke('hosts:list'),
  hostsSave: (payload) => ipcRenderer.invoke('hosts:save', payload),
  hostsDelete: (payload) => ipcRenderer.invoke('hosts:delete', payload),
  hostsSetCategories: (payload) => ipcRenderer.invoke('hosts:set-categories', payload),
  snippetsGetState: () => ipcRenderer.invoke('snippets:get-state'),
  snippetsSetState: (payload) => ipcRenderer.invoke('snippets:set-state', payload),
  quicktoolsGetState: () => ipcRenderer.invoke('quicktools:get-state'),
  quicktoolsSetState: (payload) => ipcRenderer.invoke('quicktools:set-state', payload),

  vaultStatus: () => ipcRenderer.invoke('vault:status'),
  vaultSetMaster: (payload) => ipcRenderer.invoke('vault:set-master', payload),
  vaultUnlock: (payload) => ipcRenderer.invoke('vault:unlock', payload),
  vaultReset: () => ipcRenderer.invoke('vault:reset'),
  vaultKeyList: () => ipcRenderer.invoke('vault:key-list'),
  vaultKeySave: (payload) => ipcRenderer.invoke('vault:key-save', payload),
  vaultKeyGet: (payload) => ipcRenderer.invoke('vault:key-get', payload),
  vaultKeyDelete: (payload) => ipcRenderer.invoke('vault:key-delete', payload),
  vaultKeyImportFile: () => ipcRenderer.invoke('vault:key-import-file'),

  syncLogin: (payload) => ipcRenderer.invoke('sync:login', payload),
  syncGetConfig: () => ipcRenderer.invoke('sync:get-config'),
  syncSetConfig: (payload) => ipcRenderer.invoke('sync:set-config', payload),
  syncStatus: () => ipcRenderer.invoke('sync:status'),
  syncTestConnection: () => ipcRenderer.invoke('sync:test-connection'),
  syncPullNow: () => ipcRenderer.invoke('sync:pull-now'),
  syncQueue: () => ipcRenderer.invoke('sync:queue'),
  syncClearQueue: () => ipcRenderer.invoke('sync:clear-queue'),
  syncPushNow: () => ipcRenderer.invoke('sync:push-now'),
  syncRetryFailed: () => ipcRenderer.invoke('sync:retry-failed'),
  onSyncStatus: (handler) => ipcRenderer.on('sync:status', (_event, data) => handler(data)),

  listSerialPorts: () => ipcRenderer.invoke('serial:list'),
  openSerial: (options) => ipcRenderer.invoke('serial:open', options),
  closeSerial: (payload) => ipcRenderer.invoke('serial:close', payload),
  sendSerial: (payload) => ipcRenderer.invoke('serial:send', payload),
  onSerialData: (handler) => ipcRenderer.on('serial:data', (_event, data) => handler(data)),
  onSerialError: (handler) => ipcRenderer.on('serial:error', (_event, data) => handler(data)),

  localConnect: (payload) => ipcRenderer.invoke('local:connect', payload),
  localWrite: (payload) => ipcRenderer.invoke('local:write', payload),
  localResize: (payload) => ipcRenderer.invoke('local:resize', payload),
  localDisconnect: (payload) => ipcRenderer.invoke('local:disconnect', payload),
  onLocalData: (handler) => ipcRenderer.on('local:data', (_event, data) => handler(data)),
  onLocalClose: (handler) => ipcRenderer.on('local:close', (_event, data) => handler(data)),
  onLocalError: (handler) => ipcRenderer.on('local:error', (_event, data) => handler(data)),

  sshTest: (config) => ipcRenderer.invoke('ssh:test', config),
  sshList: () => ipcRenderer.invoke('ssh:list'),
  sshConnect: (config) => ipcRenderer.invoke('ssh:connect', config),
  sshExecScript: (payload) => ipcRenderer.invoke('ssh:exec-script', payload),
  sshMetrics: (payload) => ipcRenderer.invoke('ssh:metrics', payload),
  sshWrite: (payload) => ipcRenderer.invoke('ssh:write', payload),
  sshResize: (payload) => ipcRenderer.invoke('ssh:resize', payload),
  sshDisconnect: (payload) => ipcRenderer.invoke('ssh:disconnect', payload),
  onSshData: (handler) => ipcRenderer.on('ssh:data', (_event, data) => handler(data)),
  onSshClose: (handler) => ipcRenderer.on('ssh:close', (_event, data) => handler(data)),
  onSshError: (handler) => ipcRenderer.on('ssh:error', (_event, data) => handler(data)),

  onSftpProgress: (handler) => ipcRenderer.on('sftp:progress', (_event, data) => handler(data)),
  localfsList: (payload) => ipcRenderer.invoke('localfs:list', payload),
  sftpList: (payload) => ipcRenderer.invoke('sftp:list', payload),
  sftpUpload: (payload) => ipcRenderer.invoke('sftp:upload', payload),
  sftpDownload: (payload) => ipcRenderer.invoke('sftp:download', payload),
  sftpDownloadToLocal: (payload) => ipcRenderer.invoke('sftp:download-to-local', payload),
  sftpMkdir: (payload) => ipcRenderer.invoke('sftp:mkdir', payload),
  sftpRename: (payload) => ipcRenderer.invoke('sftp:rename', payload),
  sftpDelete: (payload) => ipcRenderer.invoke('sftp:delete', payload),
})
